authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

from .forms import MyPasswordResetForm, MyPasswordChangeForm, MySetPasswordForm

urlpatterns = [
    path("login", views.log_in_user, name='login'),
    path("signup", views.RegisterView.as_view(), name='signup'),
    path("successfully-completed", views.successfully_completed, name='successfully_completed'),
    path('password-change', auth_view.PasswordChangeView.as_view(
        template_name='authentication/change_password.html', form_class=MyPasswordChangeForm,
        success_url='passwordchangedone'), name='password_change'),

    path('passwordchangedone', auth_view.PasswordChangeDoneView.as_view(
        template_name='authentication/successfully_completed.html'), name='passwordchangedone'),

    path('password-reset/', auth_view.PasswordResetView.as_view(
        template_name='authentication/password_reset.html', form_class=MyPasswordResetForm), name='password_reset'
    ),

    path('password-reset/done', auth_view.PasswordResetDoneView.as_view(
        template_name='authentication/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>', auth_view.PasswordResetConfirmView.as_view(
        template_name='authentication/password_reset_confirm.html', form_class=MySetPasswordForm),
         name='password_reset_confirm'),

    path('password-reset-complete', auth_view.PasswordResetCompleteView.as_view(
        template_name='authentication/successfully_completed.html'), name='password_reset_complete'),

    path("logout", views.logout_user, name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("cart", views.cart, name="cart"),
    path("remove_from_cart", views.remove_from_cart, name="remove_from_cart"),
    path("update_quantity", views.update_quantity, name='update_quantity'),
]

web_site_fit_line2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.urls import *

urlpatterns = [
    path('', include("main_pages.urls")),
    path('shop/', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('order/', include("order.urls")),
    path('auth/', include("authentication.urls")),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Fit Line"
admin.site.site_title = "Fit Line"
admin.site.site_index_title = "Admin area Fit Line"

authentication/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm, PasswordResetForm
from django.urls import reverse_lazy


# Class of the user login form / Клас форми для входу користувача
from django import forms
from django.contrib.auth import authenticate

# ...


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(attrs={"placeholder": "Enter your username", "required": True}),
    )

    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"placeholder": "Enter your password", "required": True}),
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if not username:
            raise forms.ValidationError("Please enter your username.")
        if not password:
            raise forms.ValidationError("Please enter your password.")

        # Authenticate the user with the provided username and password
        user = authenticate(username=username, password=password)

        # Check if the user exists and the password is correct
        if user is None or not user.check_password(password):
            raise forms.ValidationError("Invalid username or password.")

        # Return cleaned data if everything is valid
        return cleaned_data


# Class for creating a user registration form(клас для створення форми реєстрації користувача)
class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set the email field as required (Встановлює поле електронної пошти як обов'язкове)
        self.fields['email'].required = True

        # Apply the "form-input" class to visible form fields (Застосовує клас "form-input" до видимих полів форми)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-input'

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')

        # Check if a user with this email already exists (Перевіряє, чи вже існує користувач з такою електронною поштою)
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")  # Ця електронна пошта вже використовується

        return email


class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput(
        attrs={'autofocus': 'True', 'autocomplete': 'current-password', 'class': 'form-control'}))

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Добавляем атрибут "success_url" для указания URL, на который перенаправлять после успешного изменения пароля
        self.success_url = reverse_lazy('successfully-completed')


class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))


class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(
        attrs={'autocomplete': 'current-password', 'class': 'form-control'}))

    new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput(
        attrs={'autocomplete': 'current-password', 'class': 'form-control'}))

authentication/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login

from cart.models import Cart
from . import templates
from authentication.forms import LoginForm, RegisterForm
from django.views.generic import TemplateView, CreateView
from django.views import View
from django.urls import reverse_lazy
from django.contrib import messages
# Create your views here.


def log_in_user(request):
    # Initialize the context with an empty login form
    # Ініціалізуємо контекст із порожньою формою для входу
    context = {'login_form': LoginForm()}

    # Check if the request method is POST, which means a login form has been submitted
    # Перевіряємо, чи метод запиту є POST, що означає, що була надіслана форма для входу
    if request.method == 'POST':
        # Create an instance of the LoginForm with the data from the POST request
        # Створюємо екземпляр LoginForm із даними з POST запиту
        login_form = LoginForm(request.POST)

        # Check if the form data is valid
        # Перевіряємо, чи дані з форми є коректними
        if login_form.is_valid():
            # Extract the cleaned data from the form
            # Отримуємо очищені дані із форми
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            # Authenticate the user with the provided username and password
            # Аутентифікуємо користувача за вказаним ім'ям користувача та паролем
            user = authenticate(username=username, password=password)

            # If authentication is successful, log in the user and redirect to the 'index' page
            # Якщо аутентифікація пройшла успішно, логуємо користувача та перенаправляємо на сторінку 'index'
            if user:
                login(request, user)
                try:
                    cart = Cart.objects.get(session_id=request.session["nonuser"], completed=False)
                    if Cart.objects.filter(user=request.user, completed=False).exists():
                        cart.user = None
                        cart.save()

                    else:
                        cart.user = request.user
                        cart.save()


                except:
                    print("omooooooooooo")

                return redirect('index')
            else:
                # If authentication fails, update the context with the login form and an attention message
                # Якщо аутентифікація не вдалася, оновлюємо контекст із формою для входу та повідомленням про помилку
                context = {
                    'login_form': login_form,
                    'attention': f'The user with username {username} and password was not found :('
                }
        else:
            # If the form data is not valid, update the context with the login form
            # Якщо дані з форми некоректні, оновлюємо контекст із формою для входу
            context = {
                'login_form': login_form,
            }



    # Render the 'log_in.html' template with the appropriate context
    # Рендеримо шаблон 'log_in.html' із відповідним контекстом
    return render(request, 'authentication/log_in.html', context)

# def log_in_user2(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#
#             return redirect('home')
#         else:
#
#             error_message = "Invalid username or password. Please try again."
#             return render(request, 'authentication/log_in.html', {'error_message': error_message})
#
#     return render(request, 'authentication/log_in.html')


class RegisterView(CreateView):
    template_name = 'authentication/sign_up.html'
    form_class = RegisterForm

    # URL to redirect the user after successful registration
    # (URL для перенаправлення користувача після успішної реєстрації)
    success_url = reverse_lazy("successfully_completed")

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()

        # Authenticate the user (Аутентифікує користувача)
        login(self.request, user)

        return response

# class RegisterView2(TemplateView):
#     template_name = 'authentication/sign_up.html'
#
#     def get(self, request):
#         user_form = RegisterForm()
#         context = {'user_form': user_form}
#         return render(request, 'authentication/sign_up.html', context)
#
#     def post(self, request):
#         user_form = RegisterForm(request.POST)
#         if user_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             login(request, user)
#             return redirect('index')
#
#         context = {'user_form': user_form}
#         return render(request, 'authentication/sign_up.html', context)


def successfully_completed(request):
    return render(request, 'authentication/successfully_completed.html')


def logout_user(request):
    logout(request)
    return redirect('index')


# class ProfileView(View):
#     def get(self, request):
#         form = CustomerProfileForm()
#         context = {
#             'form': form,
#         }
#         return render(request, 'authentication/profile.html', context)
#
#     def post(self, request):
#         form = CustomerProfileForm(request.POST)
#         context = {
#             'form': form,
#         }
#         if form.is_valid():
#             user = request.user
#             name = form.cleaned_data['name']
#             city = form.cleaned_data['city']
#             locality = form.cleaned_data['locality']
#             branch_number = form.cleaned_data['branch_number']
#             mobile = form.cleaned_data['mobile']
#             state = form.cleaned_data['state']
#             zipcode = form.cleaned_data['zipcode']
#             comment = form.cleaned_data['comment']
#
#             reg = Customer(user=user, name=name, city=city, locality=locality, branch_number=branch_number,
#                            mobile=mobile, state=state, zipcode=zipcode, comment=comment)
#             reg.save()
#             messages.success(request, "Вітаю! Профіль успішно збережено")
#         else:
#             messages.warning(request, "Неправильні вхідні дані")
#         return render(request, 'authentication/profile.html', context)


# def address(request):
#     addresses = Customer.objects.filter(user=request.user)
#     context = {
#         'addresses': addresses,
#     }
#     return render(request, 'authentication/address.html', {'addresses': addresses})
#
#
# class UpdateAddress(View):
#     def get(self, request, pk):
#         add = Customer.objects.get(pk=pk)
#         form = CustomerProfileForm(instance=add)
#
#         return render(request, 'authentication/update_address.html', {'form': form})
#
#     def post(self, request, pk):
#         add = Customer.objects.get(pk=pk)
#         form = CustomerProfileForm(request.POST, instance=add)
#
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Адресу успішно оновлено")
#             return redirect('address')  # перенаправление на страницу адресов или другую нужную страницу
#         else:
#             messages.warning(request, "Неправильні вхідні дані")
#         return render(request, 'authentication/update_address.html', {'form': form})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('successfully_completed')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'authentication/change_password.html', {'form': form})

authentication/templates/authentication/address.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Address
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/profile.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/address.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-container">
        <div class="form-group">
            <a href="{% url 'profile' %}"><button type="submit" class="btn-submit">Profile</button></a>
            <a href="{% url 'address' %}"><button type="button" class="btn-submit ">Address</button></a>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% for ad in addresses %}
                    <div class="col-md-4 col-sm-6 col-12">
                        <div class="card">
                            <div class="card-body">
                                <h3>Адрес #{{ forloop.counter }}</h3>
                                <p>ПІБ: {{ad.name}}</p>
                                <p>Місто: {{ad.city}}</p>
                                <p>Вулиця: {{ad.locality}}</p>
                                <p>Номер Відділення (НП): {{ ad.branch_number }}</p>
                                <p>Телефон: {{ad.mobile}}</p>
                                <p>Область: {{ad.state}}</p>
                                <p>Індекс: {{ad.zipcode}}</p>
                                <p>Коментар: {{ad.comment}}</p>
                                <form action="{% url 'update_address' ad.id %}" method="post">
                                    {% csrf_token %}
                                     <input type="submit" value="Update" class="btn btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

authentication/templates/authentication/change_password.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Change Password
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/profile.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/change_password.css' %}">
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="background-container">
            <h2>Change Password</h2>
            <div class="form-container">
                <form action="" method="post" novalidate>
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_old_password">Old Password:</label>
                        <input type="password" id="id_old_password" name="old_password" class="form-control" required>
                        <small class="error-message">{{ form.old_password.errors|striptags }}</small>
                    </div>

                    <div class="form-group">
                        <label for="id_new_password1">New Password:</label>
                        <input type="password" id="id_new_password1" name="new_password1" class="form-control" required>
                        <small class="error-message">{{ form.new_password1.errors|striptags }}</small>
                    </div>

                    <div class="form-group">
                        <label for="id_new_password2">Confirm New Password:</label>
                        <input type="password" id="id_new_password2" name="new_password2" class="form-control" required>
                        <small class="error-message">{{ form.new_password2.errors|striptags }}</small>
                    </div>

                    <button type="submit" class="btn btn-submit">Change Password</button>

                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/log_in.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Log in
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/log_in.css' %}">
{% endblock %}

{% block content %}
    <div id="log-in">
        <h2>Welcome back to Fit Line!</h2>
        <p>Log in to access your account.</p>

        {% if login_form.errors %}
            <div class="error-message" style="color: red; font-size: 14px; text-align: center; margin-bottom: 10px; padding: 5px; background-color: #f8d7da; border: 1px solid #f5c6cb; border-radius: 5px;">
                <strong>Error:</strong> Please correct the following errors:
                <ul>
                    {% for field, errors in login_form.errors.items %}
                        <li>{{ field }}: {{ errors|join:", " }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}

            <label for="id_username">Username:</label>
            <input type="text" id="id_username" name="username" placeholder="Enter your username" required>

            <label for="id_password">Password:</label>
            <input type="password" id="id_password" name="password" placeholder="Enter your password" required>

            <a href="{% url 'password_reset' %}" class="forgot-password-link">Forgot Password?</a>

            <input type="submit" value="Log in">
            <a href="{% url 'signup' %}" class="register-link">Don't have an account? Sign up</a>
        </form>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Password Reset
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/change_password.css' %}">
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="background-container">
            <h2>Forgot Your Password?</h2> <!-- Обновлен заголовок -->
            <p>Enter your email below, and we'll send you a link to reset your password.</p> <!-- Добавлен текстовый блок с инструкциями -->
            <div class="form-container">
                <form action="" method="post" novalidate>
                    {% csrf_token %}

                    <div class="form-group2">
                        <label for="id_email">Email:</label>
                        <input type="email" id="id_email" name="email" class="form-control" required>
                        <small class="error-message">{{ form.email.errors|striptags }}</small>
                    </div>

                    <button type="submit" class="btn btn-submit">Send Reset Link</button>

                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Create a new password
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/change_password.css' %}">
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="background-container">
            <h2>Create your New Password</h2> <!-- Обновлен заголовок -->
            <p>Введіть новий надійний пароль, щоб гарантувати безпеку вашого облікового запису.</p> <!-- Добавлен текстовый блок с инструкциями -->
            <div class="form-container">
                <form action="" method="post" novalidate>
                    {% csrf_token %}

                   <div class="form-group2">
                        <label for="id_new_password1">New Password:</label>
                        <input type="password" id="id_new_password1" name="new_password1" class="form-control" required>
                        <small class="error-message">{{ form.new_password1.errors|striptags }}</small>
                    </div>

                    <div class="form-group2">
                        <label for="id_new_password2">Confirm New Password:</label>
                        <input type="password" id="id_new_password2" name="new_password2" class="form-control" required>
                        <small class="error-message">{{ form.new_password2.errors|striptags }}</small>
                    </div>

                    <button type="submit" class="btn btn-submit">Submit</button>

                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Password Reset Confirm
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/change_password.css' %}">
{% endblock %}

{% block content %}
     <div class="page-container">
        <div class="background-container">
            <div class="content-container">
                <h2>Надіслано електронний лист для скидання пароля</h2>
                <p>Ми надіслали вам електронного листа з інструкціями щодо зміни пароля.
                    Будь ласка, перевірте свою поштову скриньку та перейдіть за посиланням.</p>
                <p>Якщо ви не отримали листа, перевірте також папку "Спам".</p>
                <p>Якщо у вас продовжують виникати проблеми, <a href="{% url 'contact' %}"
                                                            style="color: #0dece5; text-decoration: underline;">
                    зв'яжіться з нами</a> за допомогою.</p>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/profile.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Profile
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-container">
        <div class="form-group">
            <a href="{% url 'profile' %}"><button type="submit" class="btn-submit">Profile</button></a>
            <a href="{% url 'address' %}"><button type="button" class="btn-submit ">Address</button></a>
        </div>

        <div class="form-container">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                    <button type="submit" class="btn-submit">Надіслати</button>
                </div>
                {% if form.non_field_errors %}
                    <div class="non-field-errors">
                        {% for error in form.non_field_errors %}
                            <p class="error-text">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if messages %}
                    <div class="messages">
                        {% for msg in messages %}
                            <div class="alert alert-{{ msg.tags }}" role="alert">
                                {{ msg }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/sign_up.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Sign up
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/sign_up.css' %}">
{% endblock %}

{% block content %}
    <div id="sign-up">
        <h2>Welcome to Fit Line!</h2>
        <p>Get fit and healthy with our premium sports nutrition products.</p>
        <form method="post" action="{% url 'signup' %}">
          {% csrf_token %}

          <!-- Display any errors if present (Виводить будь-які помилки, якщо вони є) -->
          {% for field in form %}
            {% if field.errors %}
              {% for error in field.errors %}
                <p class="error-message" style="color: red; font-size: 14px; text-align: center; margin-bottom: 10px; padding: 5px; background-color: #f8d7da; border: 1px solid #f5c6cb; border-radius: 5px;">{{ error }}</p>
              {% endfor %}
            {% endif %}
          {% endfor %}

          <label for="id_username">Username:</label>
          <input type="text" id="id_username" name="username" placeholder="Enter your username" required>

          <label for="id_email">Email:</label>
          <input type="email" id="id_email" class="form-input" name="email" placeholder="Enter your email" required>

          <label for="id_password1">Password:</label>
          <input type="password" id="id_password1" name="password1" placeholder="Enter your password" required autocomplete="off">

          <label for="id_password2">Confirm Password:</label>
          <input type="password" id="id_password2" name="password2" placeholder="Confirm your password" required autocomplete="off">

          <input type="submit" value="Register">
          <a href="{% url 'login' %}" class="register-link">Already registered? Log in</a>

        </form>
    </div>
{% endblock %}

authentication/templates/authentication/successfully_completed.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Successfully Completed
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/successfully_completed.css' %}">
{% endblock %}

{% block content %}
    <div class="box">
        <div class="success alert">
            <div class="alert-body">
                 Усішно виконано !
            </div>
         </div>
    </div>

{% endblock %}

authentication/templates/authentication/update_address.html
{% extends "web-site_fit_line2/base.html" %}

{% block title %}
  Update Address
{% endblock title %}

{% block additional_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/profile.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/update_address.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-container">
        <div class="form-group">
            <a href="{% url 'profile' %}"><button type="submit" class="btn-submit">Profile</button></a>
            <a href="{% url 'address' %}"><button type="button" class="btn-submit ">Address</button></a>
        </div>
    </div>

    <div class="container">
        <div class="form-container">
            <form action="" method="post">
                {% csrf_token %}
                {% for fm in form %}
                    <div class="form-group">
                        {{ fm.label_tag }}
                        {{ fm }}
                        <small class="text">{{ fm.errors|striptags }}</small>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" class="btn btn-update">Update</button>
                    <a href="{% url 'address' %}" class="btn btn-back">Back</a>
                </div>

                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>


{% endblock %}